// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// deferFunc is an autogenerated mock type for the deferFunc type
type deferFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *deferFunc) Execute() {
	_m.Called()
}

// newDeferFunc creates a new instance of deferFunc. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func newDeferFunc(t testing.TB) *deferFunc {
	mock := &deferFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
