// Code generated by protoc-gen-svc. DO NOT EDIT.
// source: pkg/pb/rpc.proto
package pb

import "google.golang.org/grpc"

func RegisterGoAmazingGrpcService(s *grpc.Server, srv GoAmazingServer) {
	RegisterGoAmazingServer(s, srv)
}
